baseRL: https://github.com/ohmyhub/drainbump
languageCode: en-us
theme: github.com/setsevireon/photophobia

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ""

languages:
  en:
    title: My drain is all bump
    weight: 1
    contentDir: content/posts

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml

params:
  favicon: null
  site_logo: null
  description: So that's what happened.
  recent_posts_number: 10

markup:
  highlight:
    style: nativeU

permalinks:
  post: '/posts/:slug'
