baseURL: "https://drain-bump.netlify.app"
title: "Drain Bump"
theme: github.com/setsevireon/photophobia

Subtitle: "What it do"
AuthorName: "Kevin"

SectionPagesMenu: main

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml

paginate: 5

enableEmoji: true
