baseURL: https://github.com/ohmyhub/drainbump
title: Drain Bump
theme: github.com/setsevireon/photophobia

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ""

contentDir: content/posts

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml

params:
  favicon: null
  site_logo: null
  description: So that's what happened.
  recent_posts_number: 10
  AuthorName: Kevin Ward

permalinks:
  posts: /:year/:month/:title/

markup:
  highlight:
    style: nativeU
